node_js:
- iojs
- '7'
deploy:
  provider: heroku
  api_key:
    secure: YM+QjuAkvib5lG2vPhTyG+AXCmq/stFwyQcacsdZnLp1a0PoiFA5gMH45afUz1jRxeHMswXjICkF+ypjZqm6HhkFtjy1PdaEaBYyjilzwa/UVsWMtZasPnlmg4XXnyKEYuQQEm4mzyjJlF8XDVCLv3RmWprkw3IKXrBrcn6c34P1IPU72KWFPtc/SoAQ3xOLoEs5Dl4SKDNJYF/6TahpwxwSPEBMBnE70Sf0gUZCM6OfesrYdwdJKp/Aw1paUCCE3XcSqFt3GD/ZRhwObjQJeBfqNen0gUdOFLEFIJtPP4C95G797+Hl2hvl1Su/FColr57NRiRfAX+E1HjRZoyotk02KhMZuaUn7OuEbFBbpytXYPabfAb2hxYw+aWNSgbBYM6t83ZmpPORCwJ5hiQt7raOifwRhcBjw7XfGz0T5c7BAiaV/enS65YOPEoTYU1eLUADNrZbLObRAMx+v5b/fAndmmVFWsTcZGXyt6MqiB/LR/Zmf0Fl9qwefuw3XtTCG4phhhKr40AiCQ6nzOwEigB6QCTyyx1M/PCySr9qFjJxmCO3I93jOkyFhh7Sob0Qwpzorzh24C+mxjQuYfDyO9TeRNbtVS+ksrO28jrOlugS3fjBhzGpKYfukvNevhQVwDG/xSPR0nMBigTUd2Gfot4WX85VQNsfgMN2wpU9ue0=
  app: limitless-eyrie-58664
  on:
    repo: harrisgeorge202/RD
