node_js:
- iojs
- '7'
deploy:
  provider: heroku
  api_key:
    secure: zsWaWUeUUKs2zM28tajwZFKSp1J64rxOmNVbVZLjKzjrHwjB/CeIvkU+klwFczcdU1PW0FSxJnKzbhAt2rbjdflzGchJpFmXs9HNQGd1fDWVQ/Iv+tMmaln+uCOi3Ngp8rfXQI2+Zt6lr9MVhOSNJIshVw0r6jB9nnpUIQx2qIoRWynVv1WB1aED0mkTudS0jrJjK3Zw/MluuqAfiLTOcbvcKdr9WwE5KAt/g4pyPfYVMZKJ2LXiJ/dAVdf5wnXhWNDtHpP7lNUG2MVz4L0AMKY5u7XAnr7OUrOT6/KtysVamESXLWgtfti4JCQKc/VwAyVMm5kTgPAP1A3BRSA1AlW9+mgq2/CtRHDO8oYxEpItBLDTgVjCzPNGwPSczswYxZ37kgn4DH8j75Qi1NEKpcvR5IsuZ8Vq2S7SFlBZYcgyJsHmujZ+lLHXho/udZSATCRueVE+xMfAktLPZJ6W6fdrFVk3lfTB7yUzeY4JwVsE7Pq+n9mHEkXVRgWBIM/NvSVLNO+j//tybxiKlNqtG2BgbdmKJwQ20t1IgFTP0seAYpl0FlfDJbs1RMPKYihFF6FeBaHEuySeaW8PIaP/7EEuNj9IkEyuojOPkNaHDwoC0RgH5HQl3FS7eUhrL5E5C4eiEiLaJ2K/qonc+wMUkw+C+9LdkppC0hhpOA2eGxw=
  app: limitless-eyrie-58664
  on:
    repo: harrisgeorge202/RD
